exclude_paths:
  # ignore undocumented test cases, etc
  - '**/src/test/**'
  # ignore unused parameters, constant conditions, etc
  - 'fake-bindings/**'
  # ignore undocumented public declarations in samples
  - 'android-sample/**'
  - 'fx-sample/**'
  - 'logic-sample/**'
