plugins {
    id 'org.jetbrains.kotlin.jvm'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation project(':persistence')
    implementation project(':extended-persistence')
    implementation project(':sql')
    implementation "junit:junit:$junit_version"
}
